# Generated by Django 4.1.1 on 2022-10-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
