# Generated by Django 4.1.1 on 2022-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuarios_rol_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='cedula',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='cedula',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='cedula',
            field=models.BigIntegerField(null=True),
        ),
    ]
