# Generated by Django 4.1.1 on 2022-10-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_familiar_cedula_medicos_cedula_pacientes_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
